[project]
name = "dbt-atree"
version = "0.1.0"
description = "A dbt project for data transformations using uv package manager"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.11",
    "dbt-duckdb>=1.9.6",
]
